application: multimutiny-cloud-reports
version: alpha-3
runtime: python27
api_version: 1
threadsafe: false # TODO: Can this safely be set to true

handlers:
- url: /
  static_files: resources/index.html
  upload: resources/index.html
  secure: always
- url: /static/
  static_dir: static
  secure: always
- url: /report/.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
